[build]
rustflags = ["-C", "target-cpu=native"]  #use all instruccions available in the CPU
rustdocflags = ["-D", "warnings"]
rustc-wrapper = "sccache"
# sccache is incompatible with incremental compilation
incremental = false
